name: 'Gosec Security Scanner'
description: 'Gosec Security Scanner'

runs:
  using: 'composite'
  steps:
    - name: Go mod download
      shell: bash
      run: go mod download

    - name: Check Go Version
      shell: bash
      run: go version

    - name: Install Gosec
      shell: bash    
      run: go install github.com/securego/gosec/v2/cmd/gosec@latest  # Install the latest version

    - name: Run Gosec Security Scanner
      shell: bash
      run: gosec -exclude G204,G301,G302,G304,G306 -tests -exclude-dir \.*test\.* ./...
