name: 'CLA Assistant'
description: 'CLA Assistant'

runs:
  using: 'composite'
  steps:
    - name: Static Code Analysis
      uses: golangci/golangci-lint-action@v6
      with:
        skip-cache: true
        args: |
          --timeout 5m --enable errcheck,gosimple,govet,ineffassign,staticcheck,typecheck,unused,gocritic,asasalint,asciicheck,errchkjson,exportloopref,forcetypeassert,makezero,nilerr,unparam,unconvert,wastedassign,usestdlibvars